name: Fetch AWS Account ID
description: >
  Resolves AWS account ID based on tower and environment
  using a centrally managed mapping file.

inputs:
  tower:
    description: "Workload tower / OU name"
    required: true
  environment:
    description: "Environment (dev, tst, ppe, prd)"
    required: true
outputs:
  account_id:
    description: "Resolved AWS account ID"
    value: ${{ steps.resolve.outputs.account_id }}

runs:
  using: composite
  steps:
    - name: Resolve AWS Account ID
      id: resolve
      shell: bash
      run: |
        PYTHON_BIN=$(command -v python3 || command -v python)

        if [ -z "$PYTHON_BIN" ]; then
          echo "ERROR: Python is required but not found on runner"
          exit 1
        fi
        ACCOUNT_ID=$("$PYTHON_BIN" "${{ github.action_path }}/scripts/get_account_id.py" \
          "${{ inputs.tower }}" \
          "${{ inputs.environment }}")
        echo "account_id=$ACCOUNT_ID" >> "$GITHUB_OUTPUT"