name: Terraform Apply
description: >
  Apply a previously generated Terraform plan in a deterministic
  and auditable manner. Assumes terraform init and authentication
  have already been performed by the caller.
author: Terraform Tooling Team

inputs:
  working_directory:
    description: Directory containing Terraform configuration
    required: true
    default: "."
  plan_file:
    description: Path to the Terraform plan file to apply (.tfplan)
    required: true

runs:
  using: composite
  steps:
    - name: Terraform apply
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set -euo pipefail
        PLAN_FILE="${{ inputs.plan_file }}"
        if [ ! -f "${PLAN_FILE}" ]; then
          echo "ERROR: Terraform plan file not found: ${PLAN_FILE}" >&2
          exit 1
        fi
        echo "Applying Terraform plan: ${PLAN_FILE}"
        terraform apply -input=false -auto-approve "${PLAN_FILE}"