name: Print Run Context
description: >
  Append a human-readable, platform-standard run context summary
  to the GitHub Actions job summary.
author: Platform Tooling Team

inputs:
  title:
    description: Title to use for the summary section
    required: false
    default: Run Context

  workload_tower:
    description: Workload tower (tu, int, cust, sec, coll, comm, fin)
    required: false
    default: ""

  environment:
    description: Target environment name (dev, tst, ppe, prd)
    required: false
    default: ""

  sub_environment:
    description: >
      Encoded sub-environment.
      prd → prb | prg
      ppe → ppb | ppg
      tst → sta | stb
    required: false
    default: ""

  application:
    description: Application, service, or module name
    required: false
    default: ""

  action:
    description: >
      High-level intent of the workflow run
      (bootstrap, terraform-plan, terraform-apply, terraform-destroy, app-build, image-scan, artifact-upload, etc.)
    required: false
    default: ""

  region:
    description: Execution or deployment region
    required: false
    default: ""

  working_directory:
    description: Working directory used by the workflow
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Validate sub-environment
      shell: bash
      run: |
        set -e

        ENV="${{ inputs.environment }}"
        SUB="${{ inputs.sub_environment }}"

        # No sub-environment → always valid
        [ -z "$SUB" ] && exit 0

        case "$ENV:$SUB" in
          prd:prb|prd:prg) exit 0 ;;
          ppe:ppb|ppe:ppg) exit 0 ;;
          tst:sta|tst:stb) exit 0 ;;
          dev:*) exit 0 ;;
          :)
            echo "sub_environment is set ('$SUB') but environment is empty"
            exit 1
            ;;
          *)
            echo "Invalid sub_environment '$SUB' for environment '$ENV'"
            exit 1
            ;;
        esac

    - name: Append run summary
      shell: bash
      env:
        TITLE: ${{ inputs.title }}
        WORKLOAD_TOWER: ${{ inputs.workload_tower }}
        ENVIRONMENT: ${{ inputs.environment }}
        SUB_ENVIRONMENT: ${{ inputs.sub_environment }}
        APPLICATION: ${{ inputs.application }}
        ACTION: ${{ inputs.action }}
        REGION: ${{ inputs.region }}
        WORKDIR: ${{ inputs.working_directory }}
        EVENT_NAME: ${{ github.event_name }}
        ACTOR: ${{ github.actor }}
        TRIGGERING_ACTOR: ${{ github.triggering_actor }}
        REF: ${{ github.ref }}
        WORKFLOW: ${{ github.workflow }}
        RUN_ID: ${{ github.run_id }}
        RUN_NUMBER: ${{ github.run_number }}
        REPOSITORY: ${{ github.repository }}
        SERVER_URL: ${{ github.server_url }}
        HEAD_REF: ${{ github.head_ref }}
        BASE_REF: ${{ github.base_ref }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        {
          echo "## ${TITLE}"
          echo ""
          echo "- Repository: ${REPOSITORY}"
          echo "- Workflow: ${WORKFLOW}"
          echo "- Run: ${SERVER_URL}/${REPOSITORY}/actions/runs/${RUN_ID} (#${RUN_NUMBER})"
          echo "- Trigger: ${EVENT_NAME}"
          echo "- Actor: ${ACTOR} (triggered by: ${TRIGGERING_ACTOR})"
          echo "- Ref: ${REF}"
          if [ "${EVENT_NAME}" = "pull_request" ] && [ -n "${PR_NUMBER}" ]; then
            echo "- Pull Request: #${PR_NUMBER} (${HEAD_REF} → ${BASE_REF})"
          fi
          if [ -n "${WORKLOAD_TOWER}${ENVIRONMENT}${SUB_ENVIRONMENT}${REGION}" ]; then
            echo ""
            echo "### Platform Context"
            [ -n "${WORKLOAD_TOWER}" ] && echo "- Workload tower: ${WORKLOAD_TOWER}"
            [ -n "${ENVIRONMENT}" ] && echo "- Environment: ${ENVIRONMENT}"
            [ -n "${SUB_ENVIRONMENT}" ] && echo "- Sub-environment: ${SUB_ENVIRONMENT}"
            [ -n "${REGION}" ] && echo "- Region: ${REGION}"
          fi
          if [ -n "${APPLICATION}${ACTION}${WORKDIR}" ]; then
            echo ""
            echo "### Workload"
            [ -n "${APPLICATION}" ] && echo "- Application: ${APPLICATION}"
            [ -n "${ACTION}" ] && echo "- Action: ${ACTION}"
            [ -n "${WORKDIR}" ] && echo "- Working directory: ${WORKDIR}"
          fi
        } >> "$GITHUB_STEP_SUMMARY"