name: AWS OIDC Two-Hop Authentication
description: >
  Performs secure two-hop AWS authentication using GitHub Actions OIDC.
  GitHub Actions first assumes an IAM role in the Organization (management)
  account using OIDC, then assumes the same role name in the target AWS account using STS role chaining.

inputs:
  target_account_id:
    description: "Target AWS account ID"
    required: true
  tower:
    description: "Workload tower / OU name"
    required: true
  environment:
    description: "Environment name (dev, tst, ppe, prd)"
    required: true
  region:
    description: "AWS region"
    required: true

outputs:
  assumed_role_arn:
    description: "Final assumed role ARN (target account)"
    value: ${{ steps.assume_target.outputs.assumed_role_arn }}

runs:
  using: composite
  steps:
    # Assume Org Account Role (OIDC)
    - name: Assume Org Account Role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::302263080338:role/iamr-${{ inputs.tower }}-${{ inputs.environment }}-deploy
        aws-region: ${{ inputs.region }}
        role-session-name: org-oidc-session
        audience: sts.amazonaws.com
        output-env-credentials: true
    # Assume Target Account Role via STS role chaining (NO OIDC)
    - name: Assume Target Account Role (STS role chaining)
      id: assume_target
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ inputs.target_account_id }}:role/iamr-${{ inputs.tower }}-${{ inputs.environment }}-deploy
        aws-region: ${{ inputs.region }}
        role-session-name: target-oidc-session
        role-chaining: true
        output-env-credentials: true