name: Terraform Plan
description: >
  Run terraform plan with a caller-provided var-file, capture outputs,
  publish summary, and upload plan artifacts.
author: Terraform Tooling Team

inputs:
  working_directory:
    description: Directory containing Terraform configuration
    required: true
    default: "."
  environment:
    description: Environment name (dev, tst, ppe, prd)
    required: true
  var_file:
    description: Path to terraform tfvars file (relative to working_directory)
    required: false
    default: ""

outputs:
  plan_status:
    description: Result of terraform plan (changes, no_changes).
    value: ${{ steps.plan.outputs.plan_status }}
  plan_exit_code:
    description: Exit code returned by terraform plan (useful with -detailed-exitcode).
    value: ${{ steps.plan.outputs.plan_exit_code }}
  plan_file:
    description: Path to the generated plan file.
    value: ${{ steps.plan.outputs.plan_file }}
  plan_text_path:
    description: Path to the rendered human-readable plan file.
    value: ${{ steps.capture.outputs.plan_text_path }}
  plan_json_path:
    description: Path to the rendered JSON plan file (empty when disabled).
    value: ${{ steps.capture.outputs.plan_json_path }}
runs:
  using: composite
  steps:
    - name: Terraform plan
      id: plan
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set +e
        ENV_NAME="${{ inputs.environment }}"
        VAR_FILE="${{ inputs.var_file }}"
        PLAN_FILE="plan-${ENV_NAME}.tfplan"
        terraform plan -input=false -no-color -detailed-exitcode -out=${PLAN_FILE} ${VAR_FILE:+-var-file=${VAR_FILE}}
        ec=$?
        if [ "$ec" -eq 0 ] || [ "$ec" -eq 2 ]; then
          status=$([ "$ec" -eq 2 ] && echo changes || echo no_changes)
          echo "plan_status=${status}" >> "$GITHUB_OUTPUT"
          echo "plan_exit_code=${ec}" >> "$GITHUB_OUTPUT"
          echo "plan_file=$(pwd)/${PLAN_FILE}" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        exit "$ec"

    - name: Capture plan outputs
      id: capture
      if: ${{ success() }}
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set -euo pipefail
        PLAN_FILE="plan-${{ inputs.environment }}.tfplan"
        terraform show -no-color "$PLAN_FILE" > plan.txt
        terraform show -json "$PLAN_FILE" > plan.json
        echo "plan_text_path=$(pwd)/plan.txt" >> "$GITHUB_OUTPUT"
        echo "plan_json_path=$(pwd)/plan.json" >> "$GITHUB_OUTPUT"

    - name: Publish plan summary
      if: ${{ success() }}
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        ENV_NAME="${{ inputs.environment }}"
        {
          echo "### Terraform plan (${ENV_NAME})"
          echo
          echo "<details><summary>View plan</summary>"
          echo
          echo '<pre>'
          cat plan.txt
          echo '</pre>'
          echo
          echo "</details>"
        } >> "$GITHUB_STEP_SUMMARY"

    # - name: Upload plan artifact
    #   if: ${{ steps.plan.outputs.plan_file != '' }}
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: plan-${{ inputs.environment }}-${{ github.run_id }}
    #     path: |
    #       ${{ steps.plan.outputs.plan_file }}
    #       ${{ steps.capture.outputs.plan_text_path }}
    #       ${{ steps.capture.outputs.plan_json_path }}
    #     if-no-files-found: ignore