name: Terraform Setup
description: >
  Prepare a repository for Terraform execution: configure Git for private modules,
  run formatting checks, initialize Terraform, and validate configuration.
author: Terraform Tooling Team

inputs:
  working_directory:
    description: Directory containing Terraform configuration
    required: true
    default: "."

  backend_config_file:
    description: Optional backend config file to pass to terraform init
    required: true
    default: ""

runs:
  using: composite
  steps:
    - name: Configure Git for private modules
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail
        if [ -n "${GITHUB_TOKEN:-}" ]; then
          git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
        fi

    - name: Terraform fmt check
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: terraform fmt -check -diff

    - name: Terraform init
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set -euo pipefail
        if [ -n "${{ inputs.backend_config_file }}" ]; then
          terraform init -input=false -reconfigure \
            -backend-config="${{ inputs.backend_config_file }}"
        else
          terraform init -input=false
        fi

    - name: Terraform validate
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: terraform validate -no-color