name: Terraform Setup
description: >-
  Prepare a repository for Terraform execution: configure Git for private modules,
  install Terraform, run fmt/validate, and invoke tfsec (always on).
author: Terraform Tooling Team
inputs:
  terraform_version:
    description: Terraform CLI version to install.
    required: false
    default: "1.10.0"

  working_directory:
    description: Directory containing Terraform configuration
    required: true
    default: "."

  backend_config_file:
    description: Optional backend config file to pass to terraform init
    required: true
    default: ""
  
  github_token:
    description: GitHub token used to configure git for private module access using Github Apps.
    required: true

runs:
  using: composite
  steps:
    - name: Configure Git for private modules
      shell: bash
      env:
        GITHUB_TOKEN: ${{ input.github_token }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
      run: |
        set -euo pipefail
        if [ -z "${GITHUB_TOKEN:-}" ]; then
          echo "ERROR: GITHUB_TOKEN not provided"
          exit 1
        fi
        # Normalize host (github.com OR an enterprise url)
        GIT_HOST="$(echo "${GITHUB_SERVER_URL}" | sed 's|https://||')"
        echo "Configuring git auth for host: ${GIT_HOST}"
        git config --global url."https://x-access-token:${GITHUB_TOKEN}@${GIT_HOST}/".insteadOf "https://${GIT_HOST}/"

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Terraform fmt check
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: terraform fmt -check -diff

    - name: Terraform init
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set -euo pipefail
        if [ -n "${{ inputs.backend_config_file }}" ]; then
          terraform init -input=false -reconfigure \
            -backend-config="${{ inputs.backend_config_file }}"
        else
          terraform init -input=false
        fi

    - name: Terraform validate
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: terraform validate -no-color